//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AcId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string BankName { get; set; }
        public Nullable<long> AccountNo { get; set; }
        public string IFSCcode { get; set; }
        public Nullable<long> AadharCardNo { get; set; }
        public string PanCardNo { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
