//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string BloodGroup { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string Address { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string Experience { get; set; }
        public string Shift { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Image { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> EmpRoleId { get; set; }
        public string ImageExtension { get; set; }
        public string ImageLocation { get; set; }
        public string Passport { get; set; }
        public string Visa { get; set; }
        public string MaritalStatus { get; set; }
    }
}
