//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public int PDId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> EmpStartDate { get; set; }
        public Nullable<System.DateTime> EmpEndDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
